"""add product catalog fields

Revision ID: 61ade43a7b98
Revises: e0d2a45f1444
Create Date: 2026-09-29 12:18:51.125657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ade43a7b98'
down_revision: Union[str, Sequence[str], None] = 'e0d2a45f1444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('sale_price_paise', sa.BigInteger(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(length=64), nullable=False))
    op.add_column('products', sa.Column('price_paise', sa.BigInteger(), nullable=False))
    op.add_column('products', sa.Column('sale_price_paise', sa.BigInteger(), nullable=True))
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    op.create_unique_constraint(op.f('uq_products_sku'), 'products', ['sku'])
    op.create_check_constraint(op.f('ck_products_price_non_negative'), 'products', 'price_paise >= 0')
    op.create_check_constraint(
        op.f('ck_products_sale_price_valid'),
        'products',
        'sale_price_paise IS NULL OR (sale_price_paise >= 0 AND sale_price_paise <= price_paise)',
    )
    op.create_check_constraint(op.f('ck_products_stock_non_negative'), 'products', 'stock_quantity >= 0')
    op.create_check_constraint(
        op.f('ck_product_variants_sale_price_valid'),
        'product_variants',
        'sale_price_paise IS NULL OR (sale_price_paise >= 0 AND sale_price_paise <= price_paise)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_product_variants_sale_price_valid'), 'product_variants', type_='check')
    op.drop_constraint(op.f('ck_products_stock_non_negative'), 'products', type_='check')
    op.drop_constraint(op.f('ck_products_sale_price_valid'), 'products', type_='check')
    op.drop_constraint(op.f('ck_products_price_non_negative'), 'products', type_='check')
    op.drop_constraint(op.f('uq_products_sku'), 'products', type_='unique')
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'sale_price_paise')
    op.drop_column('products', 'price_paise')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'brand')
    op.drop_column('product_variants', 'sale_price_paise')
    # ### end Alembic commands ###
